-- 코드를 입력하세요
# 모든 기간 총합 총 대여 횟수 >= 5
# 월 별 대여 횟수 출력
# with tmp as
#     (SELECT date_format(START_DATE, '%m') as MONTH, CAR_ID, count(HISTORY_ID) as RECORDS
#      from CAR_RENTAL_COMPANY_RENTAL_HISTORY
#      where START_DATE between '2022-08-01' and '2022-10-31'
#      group by MONTH, CAR_ID
#      order by MONTH, CAR_ID desc)
# select MONTH, CAR_ID, RECORDS
# from tmp
# group by CAR_ID
# having count(RECORDS) >= 5


WITH F AS (
    SELECT CAR_ID, COUNT(*) AS FILTER
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE EXTRACT(MONTH FROM START_DATE) IN(8,9,10)
    GROUP BY CAR_ID
    ORDER BY CAR_ID DESC
)

SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH
       , C.CAR_ID
       , COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C INNER JOIN F
ON  C.CAR_ID = F.CAR_ID 
WHERE   F.FILTER>=5 
        AND EXTRACT(MONTH FROM START_DATE) IN (8,9,10)
GROUP BY EXTRACT(MONTH FROM START_DATE), C.CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC